server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

spring:
  application:
    name: firstapp

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:file:.env[.properties]

  data:
    web:
      pageable:
        page-serialization-mode: via-dto

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OUTH_GOOGLE_CLIENT_SECRET}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_STATUS}
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    from: ${EMAIL_FROM_USERNAME}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
      # mail.smtp.ssl.trust: ${EMAIL_HOST}
      mail.debug: true

  # cache:
  #   type: caffeine
  #   cache-names: crypto-data
  #   caffeine:
  #     spec: expireAfterWrite=120s
jwt:
  secret: ${JWT_SECRET}

crypto:
  logo-dev:
    image-token: ${CRYPTO_IMAGE_TOKEN}

rayzorpay:
  api-key: ${RAYZORPAY_API_KEY}
  key-secret: ${RAYZORPAY_KEY_SECRET}

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN}


# sentry:
#   dsn: ${SENTRY_DSN_KEY}
#   send-default-pii: true
#   auth-token: ${SENTRY_AUTH_TOKEN}

cookie:
  secure: ${COOKIE_SECURE:true}

frontend:
  url: ${FRONTEND_URL}

crypto-base-url:
  binance: ${BINANCE_BASE_URL}
  binance-websocket: ${BINANCE_WEBSOCKET_URL}
  coingecko: ${COINGECKO_BASE_URL}
  exchange-rate: ${EXCHANGE_RATE_BASE_URL}
  image: ${CRYPTO_IMAGE_BASE_URL}

# Circuit Breaker config
resilience4j:
  circuitbreaker:
    instances:
      consumeCode:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      fetchAndCacheAllCryptoData:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      fetchAndCacheExchangeRate:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      getHistoricalData:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      fetchAndCacheTopCoins:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      fetchLivePrice:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      razorPayCreateOrder:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  # TimeLimiter config
  timelimiter:
    instances:
      consumeCode:
        timeoutDuration: 3s
        cancelRunningFuture: true
      fetchAndCacheAllCryptoData:
        timeoutDuration: 10s
        cancelRunningFuture: true
      fetchAndCacheExchangeRate:
        timeoutDuration: 10s
        cancelRunningFuture: true
      getHistoricalData:
        timeoutDuration: 15s
        cancelRunningFuture: true
      fetchAndCacheTopCoins:
        timeoutDuration: 15s
        cancelRunningFuture: true

  retry:
    instances:
      consumeCode:
        maxAttempts: 3
        waitDuration: 2s
      fetchAndCacheAllCryptoData:
        maxAttempts: 3
        waitDuration: 2s
      fetchAndCacheExchangeRate:
        maxAttempts: 3
        waitDuration: 2s
      getHistoricalData:
        maxAttempts: 3
        waitDuration: 2s
      fetchAndCacheTopCoins:
        maxAttempts: 3
        waitDuration: 2s
      fetchLivePrice:
        maxAttempts: 3
        waitDuration: 2s
      razorPayCreateOrder:
        maxAttempts: 3
        waitDuration: 2s

  bulkhead:
    instances:
      tradeService:
        maxConcurrentCalls: 10
        maxWaitDuration: 2s

  ratelimiter:
    instances:
      emailResetLimiter:
        limitForPeriod: 3
        limitRefreshPeriod: 1m
        timeoutDuration: 0s
