server:
  port: 8080
  tomcat:
    max-swallow-size: -1

spring:
  application:
    name: firstapp

  config:
    import: optional:file:.env[.properties]

  data:
    web:
      pageable:
        page-serialization-mode: via-dto

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OUTH_GOOGLE_CLIENT_SECRET}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: ${EMAIL_HOST}
      mail.debug: true

  # cache:
  #   type: caffeine
  #   cache-names: crypto-data
  #   caffeine:
  #     spec: expireAfterWrite=120s
jwt:
  secret: ${JWT_SECRET}

crypto:
  logo-dev:
    image-token: ${CRYPTO_IMAGE_TOKEN}

rayzorpay:
  api-key: ${RAYZORPAY_API_KEY}
  key-secret: ${RAYZORPAY_KEY_SECRET}

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN}

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.security: DEBUG
    org.hibernate: WARN
    com.practice.firstapp: WARN
